### ISSUE TITLE
Laravel 8 Guzzle 7.0.1 support

### ISSUE THREAD

**Issue by colorscream** [rossjcooper/laravel-hubspot#26]
Can you profive a support for Laravel 8?

Problem 1
- Installation request for rossjcooper/laravel-hubspot ^3.0 -> satisfiable by rossjcooper/laravel-hubspot[3.0.0].
- Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
- Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
- Can only install one of: guzzlehttp/guzzle[7.1.0, 6.5.x-dev].
- Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
- Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
- Conclusion: install guzzlehttp/guzzle 6.5.x-dev
- Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.0, 7.1.1, 7.1.x-dev].
`

**Comment by rossjcooper** [comment]
@colorscream thanks for the request, I'll make an update

**Comment by rossjcooper** [comment]
Hi @colorscream the version constraint for Guzzle 7 come from the Hubspot package, there has been an issue raised [here](https://github.com/HubSpot/hubspot-php/issues/326) but it looks like they're migrating to a new package rather than working on the one we use here.

After looking into their newer package they're using Guzzle 6 so that not much help here either.

**Comment by rossjcooper** [comment]
The Hubspot team have recently released a new major version with Guzzle 7 support, will get this updated in this package too https://github.com/HubSpot/hubspot-php/compare/v2.0.6...v3.0.0

**Comment by rossjcooper** [comment]
v4 now should fix this https://github.com/rossjcooper/laravel-hubspot/releases/tag/4.0.0
