### ISSUE TITLE
private apps

### ISSUE THREAD

**Issue by kellerkexu** [rossjcooper/laravel-hubspot#33]
Does support private apps?
Starting November 30, 2022, HubSpot API keys will no longer be able to be used as an authentication method to access HubSpot APIs.

**Comment by wgriffioen** [comment]
I've made a change to support private apps. See PR #34.

**Comment by RJaydeveloper** [comment]
Would be awesome to get this merged in asap. Thanks for committing an update to support this.

**Comment by yeasir2148** [comment]
> Would be awesome to get this merged in asap. Thanks for committing an update to support this.

Hi @RJaydeveloper : Any tentative timeline as to when this PR may be approved? Thanks for developing and maintaining the library

**Comment by RJaydeveloper** [comment]
> > Would be awesome to get this merged in asap. Thanks for committing an update to support this.
> 
> Hi @RJaydeveloper : Any tentative timeline as to when this PR may be approved? Thanks for developing and maintaining the library

@yeasir2148 I am not the developer of the package, but I am assuming it may be abandoned at this point. You may want to for it, or wait for someone to fork it and merge @wgriffioen pull request there.

**Comment by wgriffioen** [comment]
For those who want to use the changes I made in #34, you could temporarily use my fork until @rossjcooper has merged the PR.

To do this, you need to issue the following steps:

1. Add my repository to the repositories key in your composer.json file

```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/wgriffioen/laravel-hubspot.git"
    }
  ],
```

2. Change the version of the laravel-hubspot library to use my branch. This will instruct Composer to use my branch instead of the branch of @rossjcooper.

```
composer require rossjcooper/laravel-hubspot:dev-add-private-app-support
```

When the PR is merged, you can revert these changes and everything will be back to normal.

**Comment by rossjcooper** [comment]
Hi all, that PR has been merged in thank you. Please upgrade to version ^5.0  to start using private apps API keys
